DB_CONF_KEY = r".\assets\config\db_conf.key"
DB_CONF = r".\assets\config\db_conf.yaml"
DB_KEY = r".\assets\config\database.key"
DB_NAME = "password_manager"
TABLE_PASSWORD = "passwords"
CONF_PATH = r".\assets\config"
LOGS_PATH = r".\logs"